### ISSUE TITLE
Issue with flat button in light mode

### ISSUE THREAD

**Issue by maccesch** [lpotthast/leptonic#4]
<img width="302" alt="Screenshot 2023-08-15 at 12 48 29" src="https://github.com/lpotthast/leptonic/assets/380881/bdc500cb-5fcc-4a33-8d84-a819e64163d7">

**Comment by lpotthast** [comment]
Thanks for bringing this up. I updated the button styling. See https://leptonic.dev/doc/changelog.

I really hate providing these default style variants... Basically made the decision because most other component frameworks do it and it is probably expected by users to just be able to specify different styles without implementing custom stuff. But this feel so limiting. Users should be able to define all of these variants themself, but I cannot come up with a nice API for that which doesn't require much tinkering. Feel free to tell me if you have an idea of how to build a more generic and user-defineable, in terms of styling, button.

**Comment by maccesch** [comment]
Thanks for fixing this so quickly.

I totally understand your styling dislike. Indeed I have a suggestion but by no means am I sure that it's better than your current system. 

In `leptos-struct-table` we made the decision to offload styling to established CSS Frameworks. The only thing required for that is to be able to customize the classes that are applied to the various elements. 

To do that we have a classes provider trait that the user can implement. To make it easy and quick to get started we provide some default classes providers for various popular CSS frameworks. For most traditional ones they look very similar anyway.

Of course the user should still be able to add other classes to customize things through a `class` prop. Maybe there should be also an `override_class` prop in case someone wants to replace all classes for a component manually while keeping the defaults from the chosen provider for others.

The advantage here is that users can leverage their existing knowledge of one of these CSS frameworks and choose their favorite one. Or their client's favorite one. And all the complicated css variables and interdependencies are handled by somebody else. It would also help if only part of a legacy project, that uses a CSS framework already, is replaced by Leptos + Leptonic. 

The disadvantage would be that the HTML structure of components would have to be unified so it works with these frameworks. Should be possible though. [Oruga](https://oruga.io/) in Vue land does sth like this.

**Comment by maccesch** [comment]
Maybe this could be another good inspiration on this topic? https://react-spectrum.adobe.com/react-aria/react-aria-components.html
